### ISSUE TITLE
Frameworks backend

### ISSUE THREAD

**Issue by julienb86** [devs-coffee/backend-collab-chat-project#2]
Concernant le backend,
je me pose la question de l'utilisation de NestJs pour le backend => [https://nestjs.com/](url) 
voici quelques raisons:
1.  utilise TS de base: (ressemble un peu à Angular)
2. utilise express ou peut être configuré avec Fastify qui permet de gagner en perf
3.  fonctionnalités puissantes :
- injection de dépendances,
- repository pattern, 
- module de tests inclus
- migrations et utilisation de Typeorm ou Prisma en tant qu'ORM (documentation nettement mieux que Sequelize et supporte de base TS) : 
 typeorm : [https://typeorm.io/](url)
prisma: [https://www.prisma.io/](url) 
avis sur Prisma: [https://javascript.developpez.com/actu/314513/Prisma-un-ORM-de-nouvelle-generation-pour-Node-js-et-TypeScript-pour-concurrencer-TypeORM-et-Sequelize-et-devenir-la-norme-de-l-industrie/](url)

4. Peut être intéressant pour les applications qui gagnent en volume
5. Facilité pour maintenir le code

Voici un lien qui fait un comparatif entre Express et NestJs: [https://blog.logrocket.com/nestjs-vs-express-js/](url)

Je pense que ça vaut le coup de se poser la question :)

**Comment by lokkotara** [comment]
Merci beaucoup pour ces infos. Je vais jeter un oeil dessus dans la soirée ;) En tout cas ça à l'air prometteur.

**Comment by WhitedogWarren** [comment]
Effectivement ça ressemble un peu à angular.
Du coup, ça me plait bien, mais la prise en main va être plus longue, non ?
Bon, je vote pour, ça changera de node, mais ça va faire pas mal de nouveautés, pour le coup ^^

**Comment by lokkotara** [comment]
Suite au call du 04/09/2022, après concertation avec Julien et Lucas, il a été retenu de choisir Nestjs et Prisma au lieu d'Expressjs.

**Comment by WhitedogWarren** [comment]
Concernant le choix de nestjs et prisma, il a été retenu que nestjs apportait la "rigueur" du typage et de l'organisation du code que l'on avait souhaité ( et qui nous avait conduit à envisager l'usage de typescript dans express ).
De plus, prisma offre de multiples avantages qui collaient à notre projet, comme par exemple la prise en charge des DB SQL ET noSQL ( qui faciliterait donc notre éventuel passage de l'un à l'autre ).
