### ISSUE TITLE
Avoir une classe réponse applicable à tous les endpoints

### ISSUE THREAD

**Issue by julienb86** [devs-coffee/backend-collab-chat-project#4]
Avoir une classe OperationResult par ex:
isSuccess: boolean,
errorMessage: string,
result: T

**Comment by lokkotara** [comment]
Ca me paraît une bonne idée pour uniformiser tout ça ;)

**Comment by WhitedogWarren** [comment]
Très bonne idée.
Enfin, à voir comment mettre ça en place avec nestJS.
Mais les types de réponses sont définies dans un fichier spécifique, donc ça doit être simple.

**Comment by julienb86** [comment]
D accord sur le sujet,.on crée une classe OperationResult responsable de retourner un objet commun à tous les endpoints
```
OperationResult<T>
{
   IsSucceed:boolean;
   ErrorMessage : string;
   Result: T;
}
```

**Comment by WhitedogWarren** [comment]
Oui, j'ai fait le review du commit, ta soluce me va très bien.

**Comment by julienb86** [comment]
Done
