### ISSUE TITLE
Retourner des objets 'models' plutôt que les objets bdd

### ISSUE THREAD

**Issue by julienb86** [devs-coffee/backend-collab-chat-project#5]
De ce que j ai vu sur les controllers on retourne des objets entity cad qui viennent de la bdd donc avec des champs qui seront potentiellement non intéressant pour le user (createdAt, updatedAt) et d autres comme password qu'on n a pas forcément envie de retourner comme le password par ex. Donc l idée c est de retourner à l utilisateur des objets modèles qu on construit de notre côté. (Il existe les objets dto déjà dont on pourrait éventuellement se servir)

**Comment by WhitedogWarren** [comment]
Oui, c'est plutôt bizarre qu'on ne puisse pas sélectionner les champs inclus ( ou exclus ) de la réponse avec prisma.
A creuser, non ?
Mais sinon, oui, c'est même une obligation, je dirais, de ne pas retourner tous les champs, comme l'email, le hash mdp, etc.

**Comment by WhitedogWarren** [comment]
Bon, du coup c'est géré, cette histoire, non ?
